import { Niche, NicheStatus } from '../types';

export const INITIAL_NICHES: Niche[] = [
  {
    id: 'real-estate',
    nicheName: 'Real Estate',
    category: 'Property',
    icon: '🏠',
    description: 'Residential and commercial property sales and rentals.',
    targetCustomers: 'First-time homebuyers, investors, luxury searchers',
    servicesOffered: ['Property Listing', 'Market Valuation', 'Home Staging', 'Legal Support'],
    commonProblems: ['High property prices', 'Difficult mortgage process', 'Trust in agents'],
    offerIdeas: ['Free Home Valuation', '0% Processing Fee Advisory', 'VIP Pre-Launch Access'],
    googleAdsHeadlines: ['Find Your Dream Home', 'Top Real Estate Deals', 'Invest in Your Future'],
    googleAdsDescriptions: ['Looking for a luxury villa or a cozy apartment? Explore our premium listings today.', 'Expert real estate guidance for a stress-free buying experience.'],
    metaAdsTexts: ['Stop dreaming, start living! Check out our latest selection of handpicked homes that fit every budget. 🗝️✨'],
    whatsappTemplates: ['Hi [Client Name], seen this property yet? [Link] - It perfectly matches your criteria!'],
    landingPageSections: ['Featured Listings', 'Neighborhood Guide', 'Happy Homebuyers'],
    instagramPostIdeas: ['Virtual Tour Reel', 'Market Trends Update', 'Client Handover Photos'],
    reelScriptIdeas: ['3 Things to check before buying', 'Luxury tour with a catchy beat'],
    imagePromptTemplates: ['Modern luxury interior design, neutral colors, cinematic lighting, 8k', 'Suburban family home sunset exterior, photorealistic'],
    proposalPoints: ['Strategic Listing Placement', 'Professional HDR Photography', 'Social Media Campaign'],
    followUpMessages: ['Hi, hope you liked the property tour! Any thoughts on the floor plan?'],
    leadFormQuestions: ['Looking for Buy or Rent?', 'Preferred Location?', 'Budget Range?'],
    status: NicheStatus.ACTIVE,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'dental-clinic',
    nicheName: 'Dental Clinic',
    category: 'Healthcare',
    icon: '🦷',
    description: 'General, cosmetic, and emergency dental care.',
    targetCustomers: 'Families, adults seeking dental aesthetics, emergency patients',
    servicesOffered: ['Teeth Whitening', 'Root Canal', 'Implants', 'Checkups'],
    commonProblems: ['Dental anxiety', 'Pain during treatment', 'High cost of implants'],
    offerIdeas: ['20% Off First Cleaning', 'Free Implant Consultation', 'Family Dental Package'],
    googleAdsHeadlines: ['Smile Brighter Today', 'Pain-Free Dental Care', 'Voted #1 Dental Clinic'],
    googleAdsDescriptions: ['Experience gentle, modern dentistry. From whitening to implants, we care for your smile.', 'Affordable family dentistry with 5-star ratings.'],
    metaAdsTexts: ['A confident smile changes everything! Ready for a makeover? Book your free consultation today. 😁✨'],
    whatsappTemplates: ['Time for your checkup, [Client Name]! Secure your slot this Saturday.'],
    landingPageSections: ['Our Technologies', 'Doctor Profile', 'Patient Transformations'],
    instagramPostIdeas: ['Before/After Whitening', 'Fun Facts about Teeth', 'Day in the life of a Dentist'],
    reelScriptIdeas: ['How to floss correctly', 'Reaction to a smile makeover'],
    imagePromptTemplates: ['Clean modern dental clinic interior, friendly lighting', 'Close up of a perfect healthy smile, professional photography'],
    proposalPoints: ['High-Tech Diagnostic Tools', 'Insurance Assistance', 'Comprehensive Aftercare'],
    followUpMessages: ['How is your recovery going after yesterday\'s procedure?'],
    leadFormQuestions: ['Reason for visit?', 'Last dental checkup date?', 'Are you in pain?'],
    status: NicheStatus.ACTIVE,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'salon-beauty',
    nicheName: 'Salon & Beauty',
    category: 'Lifestyle',
    icon: '💇‍♀️',
    description: 'Hair, makeup, and skin beauty services.',
    targetCustomers: 'Brides, busy professionals, trend-seekers',
    servicesOffered: ['Hair Styling', 'Facials', 'Manicure', 'Makeup'],
    commonProblems: ['Unreliable stylists', 'Bad skin reactions', 'Inconsistent results'],
    offerIdeas: ['Free Hair Spa with Coloring', 'Refer a Friend: 15% Off', 'Bridal Trial Discount'],
    googleAdsHeadlines: ['Your Transformation Awaits', 'Best Hair Stylists in Town', 'Glow with BrandUp Beauty'],
    googleAdsDescriptions: ['Book your premium salon experience today. Expert hair, nails, and facials.', 'Feel revitalized with our custom beauty treatments.'],
    metaAdsTexts: ['New season, new look! ✨ Book your hair transformation with our master stylists today.'],
    whatsappTemplates: ['Ready for a glow-up? We have 2 slots left for Friday!'],
    landingPageSections: ['Style Gallery', 'Our Experts', 'Service Menu'],
    instagramPostIdeas: ['Time-lapse of hair change', 'Close up of nail art', 'Skincare routine tips'],
    reelScriptIdeas: ['Satisfying hair wash', 'Beauty transformation reveal'],
    imagePromptTemplates: ['Chic boutique salon interior, minimalist, gold accents', 'Portrait of woman with glowing skin, soft focus'],
    proposalPoints: ['Premium Product range', 'Highly Trained Staff', 'Loyalty Program Benefits'],
    followUpMessages: ['Hope you love your new look! Don\'t forget to use the serum we discussed.'],
    leadFormQuestions: ['Specific service interest?', 'Special occasion?', 'Preferred weekday?'],
    status: NicheStatus.ACTIVE,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
];
